# 服务器配置
server:
  port: 8123
  servlet:
    context-path: /api

# Spring 配置
spring:
  application:
    name: sinlei-rag-agent
    profiles:
      active: local
  mvc:
    favicon:
      enabled: false
  ai:
    dashscope:
      api-key: sk-ed9898e7d18348b2a14b89e7bbeb8731
      chat:
        options:
          model: qwen-plus

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.sinlei.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
# 日志配置
logging:
  level:
    org.springframework.ai: DEBUG
